tests:
  stage: test
  tags:
    - unit-tests
  script:
    - export PATH=$PATH:/dart/bin
    - dart down || echo 'already down'
    - dart up --dev
    - dart +phpunit --coverage-text | tee coverage.txt
    - echo Print out the coverage so gitlab\'s regex picks it up.
    - grep -P "^[^M]*Lines:\s*\d+.\d+\%" coverage.txt | sed "s/\x1B\[[0-9;]\+[A-Za-z]//g"
  after_script:
    - dart x web chmod -R a+w coverage
    - dart x web chmod -R a+w vendor
    - dart x web chmod -R a+w public
    - dart x web chmod -R a+w node_modules
    - dart x web chmod -R a+w storage
    - dart x web chmod -R a+w ../tools
    - dart down
  artifacts:
    paths:
      - web/coverage/
    expire_in: 1 day
  cache:
    paths:
      - web/vendor/

docs:
  stage: deploy
  tags:
    - doxygen
  dependencies:
    - tests
  script:
    - rm -rf /srv/coverage.gitlab.ccel.org/htdocs/robo-hummer
    - mv web/coverage/ /srv/coverage.gitlab.ccel.org/htdocs/robo-hummer
  only:
    - master
