# vim: set tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab :
version: '3.4'

services:
  web:
    build:
      context: ./container/web/
      args:
        - IMG_TAG=$IMG_TAG
      target: web
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ..:/var/www/
      - $ENV_FILE:/var/www/web/.env
      - ${DART_OVERLAY_ROBO_MEDIA}:/srv/robo-media-dart
      - /etc/hostname:/etc/host-hostname:ro # Provide the container with the host's hostname
    networks:
      - def

  mysql:
    image: ${CCEL_REGISTRY}/mysql
    volumes:
      - ${MYSQL_DIR}:/var/lib/mysql
    networks:
      - def
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

  mail:
    image: ${CCEL_REGISTRY}/mail
    volumes:
      - /etc/hostname:/etc/host-hostname:ro # Provide the container with the host's hostname
    networks:
      - def

  cron:
    build:
      context: ./container/web/
      args:
        - IMG_TAG=$IMG_TAG
      target: cron
    volumes:
      - ..:/var/www/
      - $ENV_FILE:/var/www/htdocs/api/.env
    networks:
      - def

networks:
  def:
