#!/bin/bash
# Generate a .env file for this app

cd "$(dirname "$(realpath "$0")")"

ENV_FILE_NAME=$(mktemp)                      \
	&& cp .env                $ENV_FILE_NAME \
	&& sed -i "s/##FQN##/$1/" $ENV_FILE_NAME \
	&& chmod a+r,a-w          $ENV_FILE_NAME \
	&& echo                   $ENV_FILE_NAME
